### Site metadata

# Don't make the title longer than this, otherwise it gets covered in mobile view.
title: Cloud Security Engineering
description: Mis opiniones y experiencias como security engineer

email: naberdeem@gosecurity.cloud
github_username: gosecuritycloud
discord:
linkedin:

### Build settings

url: https://gosecuritycloud.github.io
baseurl: /blogminimal

permalink: pretty

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - docs/
  - vendor/
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
